import { Ionicons } from '@expo/vector-icons';
import { Image, ScrollView, StyleSheet, Text, TouchableOpacity, View, useWindowDimensions } from 'react-native';

import loreData from '../data/lore.json';

export default function CharacterDetailsScreen({ route, navigation }) {
  const { width } = useWindowDimensions();
  const isMobile = width < 768;

  const { character, imageUrl, currentTheme = 'LIGHT' } = route.params || {};

  const attributes = character?.attributes || {};
  const charId = character?.id || 1;
  const name = attributes.name || character?.name || "UNKNOWN";
  
  const charNameLower = name.toLowerCase();
  const hasCustomLore = loreData[charNameLower];
  let lore = {};

  if (hasCustomLore) {
    lore = loreData[charNameLower];
  } else {
    const genCursing = (charId * 7) % 85 + 10;
    const genManipulation = (charId * 13) % 75 + 5;
    const genEmpathy = (charId * 3) % 95 + 5;
    const genAthleticism = (charId * 19) % 80 + 10;

    const sexTag = attributes.sex ? attributes.sex.toUpperCase() : "UNKNOWN";
    const occupationTag = attributes.occupation ? attributes.occupation.toUpperCase() : "RESIDENT";

    lore = {
      tags: [sexTag, occupationTag],
      shortDesc: `A proud citizen of South Park, Colorado. Frequently spotted around town during major municipal crises.`,
      bio: `${name} is one of the many colorful characters inhabiting the quiet mountain town of South Park. They go about their daily life trying to survive the absolute chaos generated by the local fourth graders, alien invasions, or Randy Marsh's latest hobbies.`,
      alias: attributes.religion || "None",
      age: attributes.age || "Unknown",
      grade: attributes.grade || "Unknown",
      voicedBy: attributes.voiced_by || "Matt & Trey",
      stats: {
        Cursing: genCursing,
        Manipulation: genManipulation,
        Empathy: genEmpathy,
        Athleticism: genAthleticism
      },
      quotes: [
        `"Just another normal, crazy day in South Park..."`,
        `"Mumble grumble... I hate this town sometimes."`
      ]
    };
  }
  const displayAge = lore.age || attributes.age || "Unknown";
  const displayGrade = lore.grade || attributes.grade || "Unknown";
  const displayVoicedBy = lore.voicedBy || attributes.voiced_by || "Matt & Trey";
  const isDark = currentTheme === 'DARK';
  const bgColor = isDark ? '#222' : currentTheme === 'CLASSIC' ? '#f4d03f' : '#fff';
  const textColor = isDark ? '#fff' : '#000';
  const subtextColor = isDark ? '#ccc' : '#333';
  const boxBg = isDark ? '#333' : '#fff';
  const altBoxBg = isDark ? '#444' : '#e0e0e0';
  const navBg = isDark ? '#111' : currentTheme === 'CLASSIC' ? '#f1c40f' : '#f5f5f5';

  const renderProgressBar = (label, value) => {
    let barColor = '#e74c3c';
    if (value > 80) barColor = '#17a2b8'; 
    if (value < 25) barColor = isDark ? '#666' : '#34495e';

    return (
      <View style={styles.attributeRow} key={label}>
        <View style={styles.attributeTextRow}>
          <Text style={[styles.attributeLabel, { color: textColor }]}>{label}</Text>
          <Text style={[styles.attributeValue, { color: textColor }]}>{value}/100</Text>
        </View>
        <View style={[styles.progressBarBg, { borderColor: textColor, backgroundColor: altBoxBg }]}>
          <View style={[styles.progressBarFill, { width: `${value}%`, backgroundColor: barColor, borderColor: textColor }]} />
        </View>
      </View>
    );
  };

  return (
    <View style={[styles.container, { backgroundColor: bgColor }]}>
      
      <View style={[styles.navBar, { backgroundColor: navBg, borderColor: textColor }]}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
          <Ionicons name="arrow-back" size={20} color={textColor} style={{ marginRight: 8 }} />
          <Text style={[styles.backText, { color: textColor }]}>BACK TO DEX</Text>
        </TouchableOpacity>
      </View>
      <ScrollView contentContainerStyle={[styles.scrollContent, { padding: isMobile ? 15 : 30 }]} showsVerticalScrollIndicator={false}>
        
        <View style={[styles.headerRow, { flexDirection: isMobile ? 'column' : 'row', alignItems: isMobile ? 'center' : 'flex-start', gap: isMobile ? 15 : 30 }]}>
          
          <View style={[styles.imageBox, { 
              borderColor: textColor, 
              backgroundColor: isDark ? '#2c3e50' : '#6ec3b9',
              width: isMobile ? 160 : 200,
              height: isMobile ? 160 : 200 
            }]}>
            <Image source={{ uri: imageUrl }} style={styles.image} resizeMode="contain" />
          </View>
          
          <View style={[styles.titleBox, { alignItems: isMobile ? 'center' : 'flex-start' }]}>
            <View style={[styles.tagsRow, { justifyContent: isMobile ? 'center' : 'flex-start' }]}>
              {lore.tags.map((tag, idx) => (
                <View key={idx} style={[styles.tag, { borderColor: textColor, backgroundColor: boxBg }, idx === 1 && { backgroundColor: '#c0392b' }]}>
                  <Text style={[styles.tagText, { color: textColor }, idx === 1 && { color: '#fff' }]}>{tag}</Text>
                </View>
              ))}
            </View>
            <Text style={[styles.characterName, { color: textColor, fontSize: isMobile ? 28 : 42, textAlign: isMobile ? 'center' : 'left' }]}>
              {name.toUpperCase()}
            </Text>
            <Text style={[styles.shortDesc, { color: subtextColor, textAlign: isMobile ? 'center' : 'left' }]}>
              {lore.shortDesc}
            </Text>
          </View>
        </View>

        <View style={[styles.divider, { backgroundColor: textColor }]} />

        <View style={[styles.contentRow, { flexDirection: isMobile ? 'column' : 'row', gap: isMobile ? 20 : 30 }]}>
          
          <View style={styles.leftColumn}>
            <View style={[styles.bioBox, { borderColor: textColor }]}>
              <Text style={styles.sectionTitle}>BIOGRAPHY</Text>
              <Text style={styles.bioText}>{lore.bio}</Text>
            </View>

            <View style={styles.quotesSection}>
              <Text style={[styles.sectionTitleQuotes, { color: textColor }]}>MEMORABLE QUOTES</Text>
              {lore.quotes.map((quote, idx) => (
                <View key={idx} style={[styles.quoteBox, { borderColor: textColor, backgroundColor: boxBg }]}>
                  <Text style={styles.quoteMarks}>❝</Text>
                  <Text style={[styles.quoteText, { color: textColor }]}>{quote}</Text>
                </View>
              ))}
            </View>
          </View>

          <View style={styles.rightColumn}>
            <View style={styles.statsGrid}>
              <View style={[styles.miniStatBox, { borderColor: textColor, backgroundColor: altBoxBg }]}>
                <Text style={[styles.miniStatLabel, { color: subtextColor }]}>Age</Text>
                <Text style={[styles.miniStatValue, { color: textColor }]}>{displayAge}</Text>
              </View>
              <View style={[styles.miniStatBox, { borderColor: textColor, backgroundColor: isDark ? '#2c3e50' : '#6296a6' }]}>
                <Text style={[styles.miniStatLabel, { color: isDark ? '#ccc' : '#000' }]}>Grade</Text>
                <Text style={[styles.miniStatValue, { color: isDark ? '#fff' : '#000' }]}>{displayGrade}</Text>
              </View>
              <View style={[styles.miniStatBox, { borderColor: textColor, backgroundColor: altBoxBg }]}>
                <Text style={[styles.miniStatLabel, { color: subtextColor }]}>Alias / Religion</Text>
                <Text style={[styles.miniStatValue, { color: textColor }]} numberOfLines={1}>{lore.alias || "None"}</Text>
              </View>
              <View style={[styles.miniStatBox, { borderColor: textColor, backgroundColor: altBoxBg }]}>
                <Text style={[styles.miniStatLabel, { color: subtextColor }]}>Voiced By</Text>
                <Text style={[styles.miniStatValue, { color: textColor }]} numberOfLines={1}>{displayVoicedBy}</Text>
              </View>
            </View>

            <View style={[styles.attributesBox, { borderColor: textColor, backgroundColor: boxBg, shadowColor: textColor }]}>
              <Text style={[styles.sectionTitle, { color: textColor, marginBottom: 15 }]}>ATTRIBUTES</Text>
              {Object.entries(lore.stats).map(([key, value]) => renderProgressBar(key, value))}
            </View>
          </View>

        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  navBar: {
    padding: 15,
    borderBottomWidth: 4,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
  },
  backText: {
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 1,
  },

  headerRow: {}, 
  imageBox: {
    borderWidth: 4,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  image: {
    width: '85%',
    height: '85%',
  },
  titleBox: {
    flex: 1,
  },
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 10,
  },
  tag: {
    borderWidth: 2,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  tagText: {
    fontSize: 10,
    fontWeight: '900',
    fontFamily: 'monospace',
  },
  characterName: {
    fontWeight: '900',
    letterSpacing: -1,
    marginBottom: 10,
  },
  shortDesc: {
    fontSize: 15,
    lineHeight: 22,
  },
  divider: {
    height: 4,
    marginVertical: 25,
  },
  contentRow: {},
  leftColumn: {
    flex: 1.4,
  },
  rightColumn: {
    flex: 1,
  },
  bioBox: {
    backgroundColor: '#17a2b8', 
    borderWidth: 4,
    padding: 20,
    marginBottom: 25,
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  bioText: {
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '500',
    color: '#000',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 10,
    color: '#000',
  },
  sectionTitleQuotes: {
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 15,
  },
  quotesSection: {
    gap: 12,
  },
  quoteBox: {
    flexDirection: 'row',
    borderWidth: 3,
    padding: 15,
    alignItems: 'center',
  },
  quoteMarks: {
    fontSize: 22,
    color: '#c0392b',
    marginRight: 12,
    fontWeight: '900',
  },
  quoteText: {
    fontSize: 14,
    fontWeight: '700',
    flex: 1,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 25,
  },
  miniStatBox: {
    width: '47%',
    borderWidth: 3,
    padding: 12,
  },
  miniStatLabel: {
    fontSize: 9,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    marginBottom: 3,
  },
  miniStatValue: {
    fontSize: 15,
    fontWeight: '900',
  },
  attributesBox: {
    borderWidth: 4,
    padding: 20,
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  attributeRow: {
    marginBottom: 12,
  },
  attributeTextRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  attributeLabel: {
    fontSize: 11,
    fontWeight: '900',
  },
  attributeValue: {
    fontSize: 11,
    fontWeight: '900',
  },
  progressBarBg: {
    height: 14,
    borderWidth: 2,
  },
  progressBarFill: {
    height: '100%',
    borderRightWidth: 2,
  },
});